name: glowhair
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_riverpod: ^2.5.1
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  google_fonts: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loginbg.png
    - assets/chatbotimg.png
    - assets/boyicon.png
    - assets/girlicon.png
    - assets/sampledoctor.png



