// Server/routes/telegram.js
// Enterprise-grade Telegram Bot with Gemini AI for Appointment Booking

const express = require('express');
const TelegramBot = require('node-telegram-bot-api');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const Appointment = require('../Models/Appointment');
const User = require('../Models/User');
const Patient = require('../Models/Patient');
const PatientPDF = require('../Models/PatientPDF');

const router = express.Router();

// Initialize Telegram Bot with improved polling configuration
const bot = new TelegramBot(process.env.Telegram_API, {
  polling: {
    interval: 1000,
    autoStart: true,
    params: {
      timeout: 10
    }
  }
});

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.Gemi_Api_Key);
const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

// In-memory conversation state management
const conversationState = new Map();

// Helper: Get or create conversation state
function getState(chatId) {
  if (!conversationState.has(chatId)) {
    conversationState.set(chatId, {
      step: 'idle',
      data: {},
      lastActivity: Date.now()
    });
  }
  return conversationState.get(chatId);
}

// Helper: Reset conversation state
function resetState(chatId) {
  conversationState.set(chatId, {
    step: 'idle',
    data: {},
    lastActivity: Date.now()
  });
}

// Helper: Parse date/time using Gemini AI
async function parseDateTimeWithGemini(userMessage) {
  try {
    const prompt = `
You are a date/time parser. Extract the appointment date and time from the user's message.
Current date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
Current time: ${new Date().toLocaleTimeString('en-US')}

User message: "${userMessage}"

Extract and return ONLY a JSON object with this exact format (no extra text):
{
  "date": "YYYY-MM-DD",
  "time": "HH:MM",
  "success": true
}

If the date/time cannot be parsed, return:
{
  "success": false,
  "error": "Could not understand the date/time"
}

Examples:
- "tomorrow at 3pm" → {"date": "2025-10-26", "time": "15:00", "success": true}
- "next Monday 10:30 AM" → {"date": "2025-10-28", "time": "10:30", "success": true}
- "25th December 2pm" → {"date": "2025-12-25", "time": "14:00", "success": true}
`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text().trim();

    // Extract JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.warn('Gemini returned non-JSON response:', text);
      return { success: false, error: 'Could not parse date/time from response' };
    }

    const parsed = JSON.parse(jsonMatch[0]);

    if (parsed.success) {
      // Validate date is not in the past
      const appointmentDate = new Date(`${parsed.date}T${parsed.time}`);
      if (appointmentDate < new Date()) {
        return { success: false, error: 'Date/time cannot be in the past' };
      }
    }

    return parsed;
  } catch (error) {
    console.error('Gemini parsing error:', error);
    return { success: false, error: 'Failed to parse date/time' };
  }
}

// Helper: Get default doctor
async function getDefaultDoctor() {
  try {
    const doctor = await User.findOne({ role: 'doctor' })
      .select('firstName lastName email phone')
      .sort({ createdAt: 1 });
    if (!doctor) {
      throw new Error('No doctor available');
    }
    return doctor;
  } catch (error) {
    console.error('Error fetching doctor:', error);
    throw error;
  }
}

// Helper: Check for duplicate appointments
async function checkDuplicateAppointment(telegramUserId, startAt) {
  try {
    const existingAppointment = await Appointment.findOne({
      telegramUserId,
      startAt,
      status: { $in: ['Scheduled', 'Rescheduled'] }
    });
    return existingAppointment !== null;
  } catch (error) {
    console.error('Error checking duplicates:', error);
    return false;
  }
}

// Helper: Create or get patient for Telegram user
async function getOrCreatePatient(telegramUserId, telegramUsername, telegramFirstName) {
  try {
    // Try to find existing patient by telegram ID
    let patient = await Patient.findOne({ telegramUserId });

    if (!patient) {
      // Create new patient (patientCode will be auto-generated by pre-save hook)
      patient = new Patient({
        firstName: telegramFirstName || telegramUsername || 'Telegram',
        lastName: 'User',
        phone: `telegram_${telegramUserId}`,
        email: `telegram_${telegramUserId}@telegram.user`,
        gender: 'Other', // Default, can be updated later
        address: {
          line1: 'Telegram User',
          houseNo: 'Telegram',
          street: 'User - Via Bot',
          city: '',
          state: '',
          pincode: '',
          country: 'India'
        },
        telegramUserId,
        telegramUsername,
        metadata: {
          source: 'telegram',
          createdViaBot: true
        }
      });
      await patient.save();
      console.log(`✅ Created new patient for Telegram user ${telegramUserId}`);
    }

    return patient;
  } catch (error) {
    console.error('Error getting/creating patient:', error);
    throw error;
  }
}

// Helper: Create appointment
async function createAppointment(chatId, telegramUserId, patientData) {
  try {
    const doctor = await getDefaultDoctor();
    
    // Helper function to generate patient code
    const generatePatientCode = () => {
      const timestamp = Date.now().toString(36).toUpperCase();
      const random = Math.random().toString(36).substring(2, 6).toUpperCase();
      return `PAT-TG-${timestamp}-${random}`;
    };
    
    let patient;
    
    if (patientData.isExisting && patientData.patientId) {
      // Use existing patient
      patient = await Patient.findById(patientData.patientId);
      
      if (!patient) {
        return { success: false, error: 'Patient record not found' };
      }
      
      // Update telegram info if not set
      if (!patient.telegramUserId) {
        patient.telegramUserId = telegramUserId.toString();
        patient.telegramUsername = conversationState.get(chatId)?.username;
        await patient.save();
      }
      
      console.log(`✅ Using existing patient: ${patient.firstName} ${patient.lastName}`);
    } else {
      // Create new patient
      const nameParts = patientData.fullName.trim().split(' ');
      const firstName = nameParts[0];
      const lastName = nameParts.slice(1).join(' ') || 'User';
      
      patient = new Patient({
        patientCode: generatePatientCode(),
        firstName,
        lastName,
        age: 0, // Will be updated later if needed
        gender: 'Other', // Default
        phone: patientData.phone,
        email: `telegram_${telegramUserId}@telegram.user`, // Default email
        bloodGroup: patientData.bloodGroup || 'Unknown',
        address: {
          line1: patientData.address || 'Telegram User',
          houseNo: '',
          street: '',
          city: '',
          state: '',
          pincode: '',
          country: 'India'
        },
        emergencyContact: {
          name: patientData.emergencyContactName || '',
          phone: patientData.emergencyPhone || '',
          relationship: 'Emergency Contact'
        },
        telegramUserId: telegramUserId.toString(),
        telegramUsername: conversationState.get(chatId)?.username,
        metadata: {
          source: 'telegram',
          createdViaBot: true
        }
      });
      await patient.save();
      console.log(`✅ Created new patient: ${patientData.fullName}`);
    }

    // Check for duplicates
    const isDuplicate = await checkDuplicateAppointment(
      telegramUserId.toString(), 
      patientData.dateTime
    );
    if (isDuplicate) {
      return { success: false, error: 'You already have an appointment at this time' };
    }

    // Create appointment
    const appointment = new Appointment({
      patientId: patient._id,
      doctorId: doctor._id,
      appointmentType: 'Consultation',
      startAt: patientData.dateTime,
      endAt: new Date(patientData.dateTime.getTime() + 30 * 60000), // 30 minutes duration
      location: 'Movi Innovations',
      status: 'Scheduled',
      notes: `Reason: ${patientData.reason}\nBooked via Telegram Bot`,
      telegramUserId: telegramUserId.toString(),
      telegramChatId: chatId.toString(),
      bookingSource: 'telegram'
    });

    await appointment.save();

    return {
      success: true,
      appointmentCode: appointment.appointmentCode,
      doctorName: `${doctor.firstName} ${doctor.lastName || ''}`.trim() || doctor.firstName || 'Doctor',
      patientName: patientData.fullName,
      dateTime: patientData.dateTime
    };
  } catch (error) {
    console.error('Error creating appointment:', error);
    return { success: false, error: error.message };
  }
}

// Bot command handlers
bot.onText(/\/start/, async (msg) => {
  const chatId = msg.chat.id;
  resetState(chatId);

  await bot.sendMessage(chatId,
    `🏥 *Welcome to Movi Innovations HMS*\n\n` +
    `I'm your virtual healthcare assistant. Here's what I can help you with:\n\n` +
    `📅 */book* - Book a new appointment\n` +
    `📋 */reports* - View your medical reports (after appointments)\n` +
    `🆘 */help* - Get help and information\n` +
    `❌ */cancel* - Cancel current operation\n\n` +
    `💡 *First time?* Start by booking an appointment!\n\n` +
    `*Need help?* Contact us at:\n` +
    `📞 +91-XXXXX-XXXXX\n` +
    `📧 info@karurgastro.com`,
    { parse_mode: 'Markdown' }
  );
});

bot.onText(/\/help/, async (msg) => {
  const chatId = msg.chat.id;

  await bot.sendMessage(chatId,
    `📚 *How to use this bot:*\n\n` +
    `*Available Commands:*\n` +
    `📅 /book - Book a new appointment\n` +
    `📋 /reports - View and download your medical reports\n` +
    `🆘 /help - Get help\n` +
    `❌ /cancel - Cancel current booking\n` +
    `🏠 /start - Return to main menu\n\n` +
    `*Booking Process:*\n` +
    `1️⃣ Send /book to start\n` +
    `2️⃣ Provide your details (name, age, gender, phone, etc.)\n` +
    `3️⃣ Choose appointment date and time\n` +
    `4️⃣ Confirm and receive appointment code\n\n` +
    `*Viewing Reports:*\n` +
    `1️⃣ Send /reports to see your medical reports\n` +
    `2️⃣ Select a report from the list\n` +
    `3️⃣ Download and view on your device\n\n` +
    `💡 *Tips:*\n` +
    `• Use natural language for dates: "tomorrow at 3pm"\n` +
    `• Reports are downloaded as PDF files\n` +
    `• Your reports are secure and private\n\n` +
    `Use /cancel anytime to cancel the current booking.`,
    { parse_mode: 'Markdown' }
  );
});

bot.onText(/\/cancel/, async (msg) => {
  const chatId = msg.chat.id;
  resetState(chatId);

  await bot.sendMessage(chatId, '❌ Booking cancelled. Use /book to start again.');
});

// Command: /reports - View and download medical reports
bot.onText(/\/reports/, async (msg) => {
  const chatId = msg.chat.id;
  const telegramUserId = msg.from.id;
  
  try {
    // Find patient by telegram user ID
    const patient = await Patient.findOne({ 
      telegramUserId: telegramUserId.toString() 
    });
    
    if (!patient) {
      await bot.sendMessage(chatId, 
        '❌ *No Patient Record Found*\n\n' +
        'You need to book an appointment first to access reports.\n\n' +
        '📅 Use /book to schedule your first appointment.\n\n' +
        'After your appointment, medical reports will be available here.',
        { parse_mode: 'Markdown' }
      );
      return;
    }
    
    // Check if patient has any appointments (verify they're a real patient)
    const hasAppointments = await Appointment.countDocuments({
      patientId: patient._id
    });
    
    if (hasAppointments === 0) {
      await bot.sendMessage(chatId,
        '📋 *No Appointments Yet*\n\n' +
        `Hi ${patient.firstName}! You haven't had any appointments with us yet.\n\n` +
        '📅 Use /book to schedule your first appointment.\n\n' +
        'Medical reports will be available after your visit.',
        { parse_mode: 'Markdown' }
      );
      return;
    }
    
    // Find all reports for this patient
    const reports = await PatientPDF.find({ 
      patientId: patient._id 
    })
    .sort({ uploadedAt: -1 })
    .limit(10)
    .lean();
    
    if (!reports || reports.length === 0) {
      await bot.sendMessage(chatId,
        '📋 *No Medical Reports Found*\n\n' +
        'You don\'t have any medical reports yet.\n' +
        'Reports will appear here after your appointments and tests.',
        { parse_mode: 'Markdown' }
      );
      return;
    }
    
    // Create inline keyboard with report list
    const reportButtons = reports.map((report, index) => {
      const date = new Date(report.uploadedAt).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric'
      });
      const title = report.title || 'Medical Report';
      const size = report.size ? `(${(report.size / 1024).toFixed(1)}KB)` : '';
      
      return [{
        text: `${index + 1}. ${title} - ${date} ${size}`,
        callback_data: `download_${report._id}`
      }];
    });
    
    await bot.sendMessage(chatId,
      '📋 *Your Medical Reports*\n\n' +
      `Found ${reports.length} report(s). Select one to download:`,
      {
        parse_mode: 'Markdown',
        reply_markup: {
          inline_keyboard: reportButtons
        }
      }
    );
    
    console.log(`✅ Listed ${reports.length} reports for patient ${patient._id}`);
    
  } catch (error) {
    console.error('Error fetching reports:', error);
    await bot.sendMessage(chatId,
      '❌ Error loading reports. Please try again later.\n\n' +
      'If the problem persists, contact support.'
    );
  }
});

bot.onText(/\/book/, async (msg) => {
  const chatId = msg.chat.id;
  const state = getState(chatId);

  // Store user info
  state.username = msg.from.username;
  state.firstName = msg.from.first_name;
  state.step = 'waiting_patient_type';
  state.lastActivity = Date.now();

  await bot.sendMessage(chatId,
    `👋 Welcome to Movi Innovations!\n\n` +
    `Let's book your appointment.\n\n` +
    `Are you a new patient or an existing patient?`,
    {
      parse_mode: 'Markdown',
      reply_markup: {
        inline_keyboard: [
          [{ text: '🆕 New Patient', callback_data: 'patient_type_new' }],
          [{ text: '👤 Existing Patient', callback_data: 'patient_type_existing' }]
        ]
      }
    }
  );
});

// Handle all other messages
bot.on('message', async (msg) => {
  // Skip if it's a command
  if (msg.text?.startsWith('/')) return;

  const chatId = msg.chat.id;
  const state = getState(chatId);
  const userMessage = msg.text;

  // Store user info if not already stored
  if (!state.username) {
    state.username = msg.from.username;
    state.firstName = msg.from.first_name;
  }

  try {
    switch (state.step) {
      case 'idle':
        // User sent a message without starting booking
        await bot.sendMessage(chatId,
          `👋 Hi! I can help you book appointments.\n\n` +
          `Use /book to start booking or /help for more information.`
        );
        break;

      case 'waiting_patient_id':
        // For existing patients, verify their patient ID or phone number
        const patientIdentifier = userMessage.trim();
        
        await bot.sendMessage(chatId, '🔍 Searching for your record...');
        
        // Try to find patient by phone number or ID
        let patient = await Patient.findOne({
          $or: [
            { phone: patientIdentifier },
            { _id: patientIdentifier.match(/^[0-9a-fA-F]{24}$/) ? patientIdentifier : null }
          ]
        });
        
        if (!patient) {
          await bot.sendMessage(chatId,
            `❌ Patient record not found.\n\n` +
            `Please check your phone number or patient ID and try again.\n\n` +
            `Or use /book to register as a new patient.`
          );
          break;
        }
        
        // Store patient data temporarily
        state.data.patientId = patient._id;
        state.data.age = patient.age;
        state.data.gender = patient.gender;
        state.data.phone = patient.phone;
        state.data.email = patient.email;
        state.data.bloodGroup = patient.bloodGroup;
        state.data.isExisting = true;
        state.step = 'waiting_patient_name';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId,
          `✅ *Patient Record Found!*\n\n` +
          `📱 *Phone:* ${state.data.phone}\n\n` +
          `Please confirm your *full name*:`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_patient_name':
        state.data.fullName = userMessage.trim();
        state.step = 'waiting_reason';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId,
          `Thanks, ${state.data.fullName}!\n\n` +
          `What is the *reason for your visit*?\n\n` +
          `(e.g., "Regular checkup", "Stomach pain", "Follow-up consultation", etc.)`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_full_name':
        state.data.fullName = userMessage.trim();
        state.data.isExisting = false;
        state.step = 'waiting_phone';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId, `Thanks, ${state.data.fullName}!\n\nNow, please provide your *phone number*:`, { parse_mode: 'Markdown' });
        break;

      case 'waiting_phone':
        const phone = userMessage.trim();
        if (phone.length < 10 || !/^\+?[\d\s-()]+$/.test(phone)) {
          await bot.sendMessage(chatId, `❌ Please enter a valid phone number (at least 10 digits):`);
          break;
        }
        state.data.phone = phone;
        state.step = 'waiting_blood_group';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId, 
          `Perfect! What is your *blood group*?`,
          {
            parse_mode: 'Markdown',
            reply_markup: {
              inline_keyboard: [
                [
                  { text: 'A+', callback_data: 'blood_A+' },
                  { text: 'A-', callback_data: 'blood_A-' },
                  { text: 'B+', callback_data: 'blood_B+' }
                ],
                [
                  { text: 'B-', callback_data: 'blood_B-' },
                  { text: 'O+', callback_data: 'blood_O+' },
                  { text: 'O-', callback_data: 'blood_O-' }
                ],
                [
                  { text: 'AB+', callback_data: 'blood_AB+' },
                  { text: 'AB-', callback_data: 'blood_AB-' }
                ],
                [{ text: "Don't Know", callback_data: 'blood_unknown' }]
              ]
            }
          }
        );
        break;

      case 'waiting_address':
        state.data.address = userMessage.trim();
        state.step = 'waiting_emergency_name';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId, 
          `Great! Now, please provide your *emergency contact name*:`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_emergency_name':
        state.data.emergencyContactName = userMessage.trim();
        state.step = 'waiting_emergency_phone';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId, 
          `Thanks! Now, please provide the *emergency contact phone number*:`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_emergency_phone':
        const emergencyPhone = userMessage.trim();
        if (emergencyPhone.length < 10 || !/^\+?[\d\s-()]+$/.test(emergencyPhone)) {
          await bot.sendMessage(chatId, `❌ Please enter a valid emergency contact phone number (at least 10 digits):`);
          break;
        }
        state.data.emergencyPhone = emergencyPhone;
        state.step = 'waiting_reason';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId, 
          `Excellent! What is the *reason for your visit*?\n\n` +
          `(e.g., "Regular checkup", "Stomach pain", "Follow-up consultation", etc.)`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_reason':
        state.data.reason = userMessage.trim();
        state.step = 'waiting_datetime';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId,
          `📅 Thank you! When would you like to schedule your appointment?\n\n` +
          `Please provide the date and time in natural language.\n\n` +
          `*Examples:*\n` +
          `• "tomorrow at 3pm"\n` +
          `• "next Monday 10:30 AM"\n` +
          `• "December 25th at 2pm"`,
          { parse_mode: 'Markdown' }
        );
        break;

      case 'waiting_datetime':
        // Parse date/time using Gemini AI
        await bot.sendMessage(chatId, '🤔 Understanding your request...');

        const parsed = await parseDateTimeWithGemini(userMessage);

        if (!parsed.success) {
          await bot.sendMessage(chatId,
            `❌ Sorry, I couldn't understand that date/time.\n\n` +
            `${parsed.error || 'Please try again with a clearer format.'}\n\n` +
            `Examples:\n` +
            `• "tomorrow at 3pm"\n` +
            `• "next Monday 10:30 AM"\n` +
            `• "December 25th at 2pm"\n\n` +
            `Or use /cancel to cancel.`
          );
          break;
        }

        // Store parsed date/time
        const dateTime = new Date(`${parsed.date}T${parsed.time}`);
        state.data.dateTime = dateTime;
        state.data.dateStr = dateTime.toLocaleDateString('en-US', {
          weekday: 'long',
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        });
        state.data.timeStr = dateTime.toLocaleTimeString('en-US', {
          hour: '2-digit',
          minute: '2-digit'
        });
        state.step = 'waiting_confirmation';

        // Get doctor info
        const doctor = await getDefaultDoctor();

        // Build confirmation message based on patient type
        let confirmationMsg = `✅ *Perfect! Please review your appointment details:*\n\n` +
          `👤 *Name:* ${state.data.fullName}\n` +
          `📱 *Phone:* ${state.data.phone}\n`;
        
        // Add additional fields for new patients
        if (!state.data.isExisting) {
          confirmationMsg += `🩸 *Blood Group:* ${state.data.bloodGroup || 'N/A'}\n` +
            `📍 *Address:* ${state.data.address}\n` +
            `🚨 *Emergency Contact:* ${state.data.emergencyContactName} (${state.data.emergencyPhone})\n`;
        }
        
        confirmationMsg += `📝 *Reason:* ${state.data.reason}\n\n` +
          `📅 *Date:* ${state.data.dateStr}\n` +
          `🕐 *Time:* ${state.data.timeStr}\n` +
          `👨‍⚕️ *Doctor:* Dr. ${doctor.firstName} ${doctor.lastName || ''}`.trim() + `\n` +
          `🏥 *Location:* Movi Innovations\n\n` +
          `Is everything correct?`;

        await bot.sendMessage(chatId, confirmationMsg,
          {
            parse_mode: 'Markdown',
            reply_markup: {
              inline_keyboard: [
                [{ text: '✅ Confirm & Book', callback_data: 'confirm_appointment' }],
                [{ text: '❌ Cancel', callback_data: 'cancel_appointment' }]
              ]
            }
          }
        );
        break;

      case 'waiting_confirmation':
        const lowerMsg = userMessage.toLowerCase();

        if (lowerMsg.includes('confirm') || lowerMsg.includes('yes') || lowerMsg === 'y') {
          // Create appointment
          await bot.sendMessage(chatId, '⏳ Creating your appointment...');

          const result = await createAppointment(
            chatId,
            msg.from.id,
            state.data
          );

          if (result.success) {
            await bot.sendMessage(chatId,
              `✅ *Appointment Booked Successfully!*\n\n` +
              `🎫 *Appointment Code:* ${result.appointmentCode}\n` +
              `👤 *Patient:* ${result.patientName}\n` +
              `📅 *Date:* ${state.data.dateStr}\n` +
              `🕐 *Time:* ${state.data.timeStr}\n` +
              `👨‍⚕️ *Doctor:* Dr. ${result.doctorName}\n` +
              `📍 *Location:* Movi Innovations\n\n` +
              `Please save your appointment code for reference.\n` +
              `We'll see you at your appointment!\n\n` +
              `Use /book to schedule another appointment.`,
              { parse_mode: 'Markdown' }
            );
            resetState(chatId);
          } else {
            await bot.sendMessage(chatId,
              `❌ Sorry, there was an error creating your appointment:\n\n` +
              `${result.error}\n\n` +
              `Please try again with /book`
            );
            resetState(chatId);
          }
        } else if (lowerMsg.includes('cancel') || lowerMsg.includes('no') || lowerMsg === 'n') {
          await bot.sendMessage(chatId,
            `❌ Appointment booking cancelled.\n\n` +
            `Use /book to start again.`
          );
          resetState(chatId);
        } else {
          await bot.sendMessage(chatId,
            `Please use the buttons above or reply with "confirm" or "cancel".`
          );
        }
        break;

      default:
        await bot.sendMessage(chatId,
          `I'm not sure what to do. Use /help for assistance.`
        );
        resetState(chatId);
    }
  } catch (error) {
    console.error('Error handling message:', error);
    await bot.sendMessage(chatId,
      `❌ An error occurred. Please try again later.\n\n` +
      `Use /start to restart or /help for assistance.`
    );
    resetState(chatId);
  }
});

// Handle callback queries (inline keyboard buttons)
bot.on('callback_query', async (query) => {
  const chatId = query.message.chat.id;
  const data = query.data;
  const state = getState(chatId);

  try {
    // Report download handler
    if (data.startsWith('download_')) {
      const reportId = data.replace('download_', '');
      
      try {
        // Fetch the report from database
        const report = await PatientPDF.findById(reportId);
        
        if (!report) {
          await bot.answerCallbackQuery(query.id, {
            text: '❌ Report not found',
            show_alert: true
          });
          return;
        }
        
        // Verify patient access (security check)
        const patient = await Patient.findOne({
          _id: report.patientId,
          telegramUserId: query.from.id.toString()
        });
        
        if (!patient) {
          await bot.answerCallbackQuery(query.id, {
            text: '⚠️ Access denied - not your report',
            show_alert: true
          });
          console.warn(`⚠️ Unauthorized download attempt: User ${query.from.id} tried to access report ${reportId}`);
          return;
        }
        
        // Send "preparing" message
        await bot.answerCallbackQuery(query.id, {
          text: '⏳ Preparing your report...'
        });
        
        await bot.sendMessage(chatId, '⏳ *Downloading your report...*\nPlease wait...', {
          parse_mode: 'Markdown'
        });
        
        // Check file size (Telegram limit is 50MB)
        const fileSizeMB = report.size / (1024 * 1024);
        if (fileSizeMB > 50) {
          await bot.sendMessage(chatId,
            '❌ *File too large*\n\n' +
            `This report is ${fileSizeMB.toFixed(2)}MB which exceeds Telegram's 50MB limit.\n\n` +
            'Please contact the hospital to receive this report via email.',
            { parse_mode: 'Markdown' }
          );
          return;
        }
        
        // Send the document
        await bot.sendDocument(chatId, report.data, {
          caption: 
            `📄 *${report.title || 'Medical Report'}*\n\n` +
            `📅 *Uploaded:* ${new Date(report.uploadedAt).toLocaleDateString('en-IN', { 
              day: '2-digit', 
              month: 'long', 
              year: 'numeric' 
            })}\n` +
            `📊 *Size:* ${(report.size / 1024).toFixed(2)} KB\n` +
            `📝 *File:* ${report.fileName}`,
          filename: report.fileName,
          parse_mode: 'Markdown'
        }, {
          contentType: report.mimeType || 'application/pdf'
        });
        
        await bot.sendMessage(chatId,
          '✅ *Report sent successfully!*\n\n' +
          '💡 You can download it from the file above.\n' +
          'Use /reports to view more reports.',
          { parse_mode: 'Markdown' }
        );
        
        console.log(`✅ Report downloaded: ${reportId} by patient ${patient._id}`);
        
      } catch (downloadError) {
        console.error('Error downloading report:', downloadError);
        await bot.answerCallbackQuery(query.id, {
          text: '❌ Download failed',
          show_alert: true
        });
        await bot.sendMessage(chatId,
          '❌ *Failed to download report*\n\n' +
          'There was an error sending your report. Please try again later.\n\n' +
          'If the problem persists, contact support.',
          { parse_mode: 'Markdown' }
        );
      }
      
      return; // Exit early for download handler
    }
    
    // Patient type selection
    if (data.startsWith('patient_type_')) {
      const patientType = data.replace('patient_type_', '');
      
      await bot.answerCallbackQuery(query.id);
      await bot.editMessageReplyMarkup(
        { inline_keyboard: [] },
        {
          chat_id: chatId,
          message_id: query.message.message_id
        }
      );
      
      if (patientType === 'new') {
        // New patient - ask for full name
        state.step = 'waiting_full_name';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId,
          `✅ *New Patient Registration*\n\n` +
          `Please provide your *full name*:`,
          { parse_mode: 'Markdown' }
        );
      } else {
        // Existing patient - ask for patient ID or phone
        state.step = 'waiting_patient_id';
        state.lastActivity = Date.now();
        
        await bot.sendMessage(chatId,
          `✅ *Existing Patient*\n\n` +
          `Please provide your *phone number* or *patient ID* to look up your record:`,
          { parse_mode: 'Markdown' }
        );
      }
    }
    
    // Blood group selection (for new patients)
    else if (data.startsWith('blood_')) {
      const bloodGroup = data.replace('blood_', '');
      state.data.bloodGroup = bloodGroup === 'unknown' ? 'Unknown' : bloodGroup;
      state.step = 'waiting_address';
      state.lastActivity = Date.now();
      
      await bot.answerCallbackQuery(query.id);
      await bot.editMessageText(
        `✅ Blood Group: ${state.data.bloodGroup}`,
        {
          chat_id: chatId,
          message_id: query.message.message_id
        }
      );
      await bot.sendMessage(chatId, 
        `Great! Now, please provide your *address*:`,
        { parse_mode: 'Markdown' }
      );
    }
    
    // Appointment confirmation
    else if (data === 'confirm_appointment') {
      await bot.answerCallbackQuery(query.id, { text: 'Booking your appointment...' });
      await bot.editMessageReplyMarkup(
        { inline_keyboard: [] },
        {
          chat_id: chatId,
          message_id: query.message.message_id
        }
      );
      
      await bot.sendMessage(chatId, '⏳ Creating your appointment...');

      const result = await createAppointment(
        chatId,
        query.from.id,
        state.data
      );

      if (result.success) {
        await bot.sendMessage(chatId,
          `✅ *Appointment Booked Successfully!*\n\n` +
          `🎫 *Appointment Code:* ${result.appointmentCode}\n` +
          `👤 *Patient:* ${result.patientName}\n` +
          `📅 *Date:* ${state.data.dateStr}\n` +
          `🕐 *Time:* ${state.data.timeStr}\n` +
          `👨‍⚕️ *Doctor:* Dr. ${result.doctorName}\n` +
          `📍 *Location:* Movi Innovations\n\n` +
          `💡 Please save your appointment code for reference.\n`+
          `We'll see you at your appointment!\n\n` +
          `Use /book to schedule another appointment.`,
          { parse_mode: 'Markdown' }
        );
        resetState(chatId);
      } else {
        await bot.sendMessage(chatId,
          `❌ Sorry, there was an error creating your appointment:\n\n` +
          `${result.error}\n\n` +
          `Please try again with /book`
        );
        resetState(chatId);
      }
    }
    
    // Appointment cancellation
    else if (data === 'cancel_appointment') {
      await bot.answerCallbackQuery(query.id, { text: 'Booking cancelled' });
      await bot.editMessageReplyMarkup(
        { inline_keyboard: [] },
        {
          chat_id: chatId,
          message_id: query.message.message_id
        }
      );
      await bot.sendMessage(chatId,
        `❌ Appointment booking cancelled.\n\n` +
        `Use /book to start again.`
      );
      resetState(chatId);
    }
    
  } catch (error) {
    console.error('Error handling callback query:', error);
    await bot.answerCallbackQuery(query.id, { text: 'An error occurred' });
  }
});

// Clean up old conversation states (every 30 minutes)
setInterval(() => {
  const now = Date.now();
  const timeout = 30 * 60 * 1000; // 30 minutes

  for (const [chatId, state] of conversationState.entries()) {
    if (now - state.lastActivity > timeout) {
      conversationState.delete(chatId);
      console.log(`🧹 Cleaned up stale conversation state for chat ${chatId}`);
    }
  }
}, 30 * 60 * 1000);

// Error handling
bot.on('polling_error', (error) => {
  // Ignore common network errors that auto-recover
  if (error.code === 'EFATAL' || error.code === 'ECONNRESET') {
    console.warn('⚠️ Telegram polling connection error (will auto-recover):', error.message);
    return;
  }
  console.error('❌ Telegram Bot Polling Error:', error);
});

bot.on('error', (error) => {
  console.error('❌ Telegram Bot Error:', error);
});

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('Stopping Telegram bot...');
  bot.stopPolling();
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.log('Stopping Telegram bot...');
  bot.stopPolling();
  process.exit(0);
});

console.log('✅ Telegram Bot initialized successfully');

// Express route for webhook (optional, if switching to webhook mode)
router.post('/webhook', async (req, res) => {
  try {
    bot.processUpdate(req.body);
    res.sendStatus(200);
  } catch (error) {
    console.error('Webhook error:', error);
    res.sendStatus(500);
  }
});

// Health check endpoint
router.get('/health', (req, res) => {
  res.json({
    status: 'running',
    bot: bot.isPolling() ? 'polling' : 'stopped',
    conversations: conversationState.size
  });
});

module.exports = router;
